# Generated by Django 5.0.8 on 2024-08-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('original_price', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('save_price', models.IntegerField(default=0)),
                ('validate_condition', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('categories', models.CharField(blank=True, default='', max_length=100)),
                ('expire_date', models.DateTimeField(blank=True)),
                ('produce_date', models.DateTimeField(blank=True)),
                ('product_photo_location', models.CharField(blank=True, default='', max_length=200)),
                ('prices', models.ManyToManyField(null=True, to='woolworths.productprice')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woolworths.productitem')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
