# Generated by Django 5.0.8 on 2024-08-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolworths', '0002_alter_productitem_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('cardnumber', models.CharField(max_length=100)),
                ('expirary_date', models.DateTimeField()),
                ('cvc', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trolley',
            name='checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trolley',
            name='selected_unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woolworths.productitem'),
        ),
        migrations.CreateModel(
            name='TrolleyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='temp', max_length=50)),
                ('notes', models.CharField(blank=True, default='', max_length=50)),
                ('items', models.ManyToManyField(null=True, to='woolworths.trolley')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woolworths.creditcard')),
                ('trolley', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woolworths.trolleylist')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
